repository:
  # See https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#edit for all available settings.

  # A short description of the repository that will show up on GitHub
  # description: TBD ...

  # A URL with more information about the repository
  # homepage: https://auro.alaskaair.com/components/auro/[name]

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: true

  # Updates the default branch for this repository.
  default_branch: main

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: false

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: false

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

branches:
  - name: main
    # https://developer.github.com/v3/repos/branches/#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # The number of approvals required. (1-6)
        required_approving_review_count: 1
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: true
        # Blocks merge until code owners have reviewed.
        require_code_owner_reviews: true
      # Required. Require status checks to pass before merging. Set to null to disable
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: true
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: false
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions: null

# Labels: define labels for Issues and Pull Requests
labels:
  - name: duplicate
    color: 'cde6ff'
    description: This Issue or Pull Request already exists
  - name: good first issue
    color: '6bb7fb'
    description: Good for newcomers
    aliases:
    - beginner-friendly
    - beginner
    - good-starter-issue
    - good for beginner
    - Good for beginners
    - starter-issue
    - starter
  - name: help wanted
    color: '2492eb'
    description: Extra attention is needed, this user requires assistance to complete
      the work
  - name: released
    color: 'A9A9A9'
    description: Completed work has been released
  - name: 'Status: Work In Progress'
    description: Issue or Pull Request work is in Progress
    color: 'c0e585'
  - name: 'Status: Review Needed'
    color: '91be62'
    description: Work is completed, user is requesting feedback
  - name: 'Status: Complete'
    color: '5e8741'
    description: Owner has completed work and considers it ready to be merged
  - name: 'Status: Blocked'
    color: 'df0b37'
    description: Progress on the issue is Blocked, immediate attention is required
    aliases:
    - blocked
  - name: 'Abandoned'
    color: '156fad'
    description: The issue or Pull Request is wontfix
    aliases:
    - wontfix
    - invalid
  - name: 'Type: Bug'
    color: 'df0b37'
    description: Bug or Bug fixes
    aliases:
    - bug
  - name: 'Type: Feature'
    color: 'e5ad07'
    description: New Feature
    aliases:
    - enhancement
  - name: 'Type: Design'
    color: 'e5ad07'
    description: New Design
    aliases:
    - enhancement
  - name: 'Type: Content'
    color: 'ffd200'
    description: Adding or editing content
    aliases:
    - enhancement
  - name: 'Type: Refactoring'
    color: 'ffdb67'
    description: A code change that neither fixes a bug nor adds a feature
    aliases:
    - refactor
  - name: 'Type: Testing'
    color: 'fff0cd'
    description: Adding missing tests or correcting existing tests
    aliases:
    - test
    - testing
  - name: 'Type: Documentation'
    color: 'f26135'
    description: Documentation only changes
    aliases:
    - documents
    - document
  - name: 'Type: CI'
    color: 'b83302'
    description: Changes to CI configuration files and scripts
    aliases:
    - ci
  - name: 'Question'
    color: 'b83302'
    description: Further information is requested
    aliases:
  - name: 'Type: Dependencies'
    color: 'b83302'
    description: Pull requests that update a dependency file
    aliases:
    - dependencies
  - name: 'Type: UI Update'
    color: 'b83302'
    description: Changes to the user interface
    aliases:
    - dependencies
